# Generated by Django 2.2.4 on 2019-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, choices=[('a', '媒體業'), ('b', '服務業'), ('c', 'AI公司'), ('d', '政府單位'), ('e', '教育機構'), ('z', '其他')], default='z', max_length=1)),
                ('description', models.CharField(max_length=64)),
            ],
        ),
    ]
