# Generated by Django 2.2.4 on 2019-12-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20191204_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('a', '拜訪'), ('b', '報價'), ('c', '訂單'), ('d', '設計中'), ('e', '交貨'), ('z', '結案')], max_length=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.profile')),
            ],
        ),
    ]
