# Generated by Django 2.2.4 on 2019-12-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
