# Generated by Django 2.2.4 on 2019-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_project_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sales',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='technical',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
