# Generated by Django 2.2.4 on 2019-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20191205_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
