# Generated by Django 2.2.4 on 2020-01-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_project_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('department', models.CharField(blank=True, choices=[('a', '技術部'), ('b', '業務部'), ('c', '管理部')], max_length=1)),
                ('boss0', models.IntegerField(blank=True, max_length=2)),
                ('boss1', models.IntegerField(blank=True, max_length=2)),
                ('boss2', models.IntegerField(blank=True, max_length=2)),
            ],
            options={
                'permissions': (('can_check_others', 'has staffs work for self'),),
            },
        ),
    ]
