# Generated by Django 2.2.4 on 2020-01-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200106_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='boss0',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='boss1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='boss2',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
